- README.md
- packages/docworker/package.json
- packages/docworker/tsconfig.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
More type checking, more linting.
> type check the cloudflare worker, docworker

- README.md
- package.json
- packages/dev-server-kernel-ls-client/src/cleanup-state.ts
- packages/dev-server-kernel-ls-client/src/mod.ts
- packages/schema/src/schema.ts
- packages/web-client/src/Root.tsx
- packages/web-client/src/components/notebook/Cell.tsx
- packages/web-client/src/components/notebook/NotebookList.tsx
- packages/web-client/src/components/notebook/NotebookViewer.tsx
- packages/web-client/src/util/store-id.ts
- reset-local-storage.cjs
- start-dev.sh
- Confusing `NOTEBOOK_ID` vs `STORE_ID` relationship
- No kernel lifecycle tracking - unclear which kernels are active
- Direct event processing instead of proper work queue
- Manual kernel management with no session isolation
- `NOTEBOOK_ID = STORE_ID` - one notebook per store
- URL routing: `?notebook=notebook-id`
- All events scoped to single notebook database
```
cellExecutionRequested → executionRequested → executionAssigned → executionStarted → executionCompleted
```
- Kernels claim work from queue instead of processing all events
- Session-based assignment (foundation for future auth enforcement)
- Prevents multiple kernels racing on same execution
- Each kernel restart gets unique `sessionId`
- 30s heartbeat to track active kernels
- Session IDs recorded in queue assignments
- …
> Simplify Notebook/Store ID and Add Execution Queue

- HANDOFF.md
- packages/dev-server-kernel-ls-client/src/mod.ts
> Kernel fixups

- packages/web-client/src/components/notebook/AiCell.tsx
- packages/web-client/src/components/notebook/Cell.tsx
- packages/web-client/src/components/notebook/NotebookViewer.tsx
Fixes shift-enter behavior for running a cell and moving down.
> clean up some cell execution ux

- packages/dev-server-kernel-ls-client/src/mod-reactive.ts
- packages/dev-server-kernel-ls-client/src/pyodide-kernel.ts
- packages/dev-server-kernel-ls-client/test/pyodide-kernel.test.ts
- packages/docworker/src/index.ts
- packages/schema/src/build-time-validation.ts
- packages/schema/src/index.ts
- packages/schema/src/types.ts
- packages/schema/test/schema.test.ts
- packages/web-client/src/components/notebook/AiCell.tsx
- packages/web-client/src/components/notebook/Cell.tsx
- packages/web-client/src/components/notebook/NotebookViewer.tsx
- packages/web-client/src/components/notebook/RichOutput.tsx
- packages/web-client/src/components/notebook/SqlCell.tsx
> More typing

- packages/web-client/src/components/notebook/Cell.tsx
> make bg of output same as main bg for visual distinction

- packages/dev-server-kernel-ls-client/src/mod-reactive.ts
First pass at shoving notebook context in for the AI cells to "see".
Note: there's no tool use yet so the agent can't actually create cells.
> Shove notebook context in

- HANDOFF.md
> document kernel restart issue in docs

- packages/dev-server-kernel-ls-client/src/index.ts
- packages/dev-server-kernel-ls-client/src/kernel-adapter.ts
- packages/dev-server-kernel-ls-client/src/openai-client.ts
- packages/dev-server-kernel-ls-client/test/openai-client.test.ts
- packages/dev-server-kernel-ls-client/test/tool-calling.test.ts
- packages/web-client/src/components/notebook/AiCell.tsx
- packages/web-client/src/components/notebook/RichOutput.tsx
> Tools for AI

- docs/ai-context-visibility.md
- packages/dev-server-kernel-ls-client/src/kernel-adapter.ts
- packages/web-client/src/components/notebook/AiCell.tsx
- packages/web-client/src/components/notebook/Cell.tsx
- packages/web-client/src/components/notebook/NotebookViewer.tsx
- packages/web-client/src/components/notebook/SqlCell.tsx
- shared/schema.ts
> AI context selection

- packages/web-client/src/Root.tsx
Finally getting out of the prototyping stages
> Show "Loading Anode"

- packages/web-client/src/components/notebook/AiCell.tsx
- packages/web-client/src/components/notebook/Cell.tsx
- packages/web-client/src/components/notebook/NotebookViewer.tsx
- packages/web-client/src/components/notebook/SqlCell.tsx
- packages/web-client/src/index.css
Fixes responsive behavior to use input device detection rather than screen size, plus eliminates mobile horizontal overflow.
**Pointer Detection**: Uses CSS media queries `(hover: none) and (pointer: coarse)` for touch devices vs `(hover: hover) and (pointer: fine)` for mouse devices. Now landscape phones get mobile UI while small desktop windows get desktop UI.
**Mobile Overflow Fix**: Changed notebook container padding from `p-3 sm:p-4` to `px-0 py-3 sm:p-4`. Cells with negative margins can now properly extend to screen edges without causing horizontal scroll.
**iOS Font Fix**: Scoped 16px textarea font size to iOS Safari only, preventing desktop font jumping on window resize.
> Pointer-Based Responsive Design & Mobile Layout Fix

- packages/web-client/src/Root.tsx
- Move LiveStoreProvider inside AuthGuard component
- Prevents race condition where LiveStore connects before auth is validated
- Fixes 'backend head > local head' error during boot
- Auth token is now obtained after authentication state is confirmed
- Resolves issue where client connects to existing backend data without proper auth context
> fix: ensure authentication completes before LiveStore initialization

- src/Root.tsx
- src/components/notebook/DebugPanel.tsx
- src/components/notebook/NotebookViewer.tsx
- Create side-by-side layout when debug mode enabled (debug panel on right)
- Show live notebook data: cells, runtime sessions, execution queue, store info
- Add debug actions: download SQLite DB, download eventlog DB
- Set global variables: store, tables, schema, events for console debugging
- Display organized console.table with copy-paste ready LiveStore commands
- Include FPS meter in corner
- Development-only with proper tree-shaking for production builds
> Anode Debug Panel

- .vscode/extensions.json
- .vscode/settings.json
Features:
- Extensions:
- Add pretty ts error errors on hover
- Add prettier
- Add tailwind
- Settings:
- Ignore pnpm lock file when doing file search
- Fix squiggles in CSS from tailwind:
- <img width="587" alt="Screenshot 2025-06-27 at 10 17 26 AM" src="https://github.com/user-attachments/assets/97e81540-6d75-47de-8bfc-160204a19ea6" />
- allow tailwind autocomplete in `cva` funcs:
- <img width="571" alt="Screenshot 2025-06-27 at 9 29 31 AM" src="https://github.com/user-attachments/assets/e882fda4-b4d7-4dd7-9c22-bfc2bc743040" />
> Add .vscode

- package.json
Can help us reduce unnecessary renders that will slow down the product
https://github.com/user-attachments/assets/405ebabd-c59f-4fae-962a-8a12a64a45f5
> Add react-scan

- src/components/notebook/NotebookViewer.tsx
This isn't the ideal way to do this, but for now it works fine
https://github.com/user-attachments/assets/46742789-3f0c-4d32-b949-41acf30e614f
Combined w/ #121, it creates a nice experience
> Auto focus first button

- src/components/notebook/AiCell.tsx
- src/components/notebook/Cell.tsx
- src/components/notebook/SqlCell.tsx
- src/hooks/useCellKeyboardNavigation.ts
https://github.com/user-attachments/assets/96704f7c-d3ad-4263-8414-8f1f6e37c652
> Backspace deletes a cell if it's empty

- src/hooks/useCellKeyboardNavigation.ts
Make it match the codemirror shortcuts
> Use cmd-enter / shift-enter shortcuts for exection

- package.json
- pnpm-lock.yaml
- src/components/notebook/AiCell.tsx
- src/components/notebook/Cell.tsx
- src/components/notebook/CellBase.tsx
- src/components/notebook/Editor.tsx
- src/components/notebook/SqlCell.tsx
- src/components/notebook/codemirror/CodeMirrorEditor.tsx
- src/components/notebook/codemirror/baseExtensions.ts
- src/index.css
- [replace codemirror basicSetup with a custom extension list](https://github.com/runtimed/anode/pull/135/commits/147f2f910052f3eed4f61eea2554dc074f165e56)
- [undo custom autofocus logic](https://github.com/runtimed/anode/pull/135/commits/23fb40c29528184e5b73e126799041b9a484fbea)
[23fb40c](https://github.com/runtimed/anode/pull/135/commits/23fb40c29528184e5b73e126799041b9a484fbea)
- [Use common Textarea component for AICell](https://github.com/runtimed/anode/pull/135/commits/2b70d01a4e2eb3de1322b568a5c769e2e21a44b5)
[2b70d01](https://github.com/runtimed/anode/pull/135/commits/2b70d01a4e2eb3de1322b568a5c769e2e21a44b5)
- [Fix code alignment w/ play btn, and remove dotted border](https://github.com/runtimed/anode/pull/135/commits/9b9e6e463f5e62f6f5dacd1d574f60a0aa64fe8a) …
> Replace codemirror basicSetup with a custom extension list

- package.json
- pnpm-lock.yaml
- src/components/notebook/Cell.tsx
- src/components/notebook/Editor.tsx
- src/components/notebook/NotebookViewer.tsx
- src/components/notebook/VirtualizedCellList.tsx
- src/components/outputs/MarkdownRenderer.tsx
- src/hooks/useCellFocus.ts
- src/hooks/useCellKeyboardNavigation.ts
This takes us from thousands of seconds for Interaction to Next Paint to 176 ms.
> Virtualize the notebook cells

- package.json
- pnpm-lock.yaml
- src/components/notebook/RichOutput.tsx
- src/components/outputs/AiToolResultOutput.tsx
- src/components/outputs/index.ts
- src/util/prefetch.ts
- test/components/outputs/AiToolResultOutput.test.tsx
- test/setup.ts
- Implement `application/vnd.anode.aitool.result+json` with a basic little UI
> Add AiToolResultOutput component for minimal tool result rendering

- src/components/notebook/Cell.tsx
- src/components/notebook/NotebookViewer.tsx
Adds interrupt/cancellation to Anode.
> Add execution interrupt functionality to notebook UI

- src/components/notebook/AiCell.tsx
Adds a simple stop button to AI Cells when running to be able to interrupt the agent.
> Stop AI in its tracks

- .env.example
- package.json
- vite.config.ts
Note: I didn't prefix with VITE_ so that it wouldn't get bundled on production builds.
> accept an ANODE_DEV_SERVER_PORT for the vite server

- package.json
- pnpm-lock.yaml
Bump the runt schema today just to move it along.
> update to latest runt schema

- AGENTS.md
- CONTRIBUTING.md
- README.md
- package.json
- pnpm-lock.yaml
- src/components/notebook/AiCell.tsx
- src/components/notebook/VirtualizedCellList.tsx
- src/util/ai-models.ts
Groups models by provider and filters to show only tools-capable models. Removes unnecessary UI elements for cleaner model selection experience.
> Improve AI model selection UI with dynamic discovery

- src/components/notebook/codemirror/baseExtensions.ts
Just makes the cursor appear more rapidly when you move from one cell to another.
> Reset cursor animation on focus

- .env.example
- README.md
Fixed the onboarding documentation
> Update environment variables and README documentation

- package.json
- pnpm-lock.yaml
- src/Root.tsx
- src/components/notebook/AiCell.tsx
- src/components/notebook/Cell.tsx
- src/components/notebook/Editor.tsx
- src/components/notebook/NotebookViewer.tsx
- src/components/notebook/SqlCell.tsx
- src/components/notebook/VirtualizedCellList.tsx
- src/components/notebook/shared/OutputsErrorBoundary.tsx
- src/hooks/useCellOutputs.tsx
> Add error boundary logic

- src/components/notebook/DebugPanel.tsx
https://github.com/user-attachments/assets/a7e5c534-7554-46ad-8cc8-b6032316c7f0
> Add link to devtools

- package.json
- pnpm-lock.yaml
- src/Root.tsx
- src/components/notebook/DebugPanel.tsx
- src/components/notebook/NotebookViewer.tsx
- test/edge-cases.test.ts
- test/integration/execution-flow.test.ts
Follow on PR to match https://github.com/runtimed/runt/pull/107, https://github.com/runtimed/runt/pull/108, https://github.com/runtimed/runt/pull/109.
> Update runt schema upsert fix

- src/components/notebook/cell/shared/CellTypeSelector.tsx
- vite.config.ts
Fixes Cloudflare deployment issues introduced in #229 and improves development stability.
- Configure Vite Cloudflare plugin to use existing `wrangler.toml` instead of generating config
- Resolves "You have specified the environment 'production', but are using a redirected configuration" error
- Allows normal deployment process with `pnpm run deploy:production` to work
- Ignore `.env*` files from Vite hot reload to prevent Miniflare crashes
- Eliminates "Cannot read properties of undefined (reading 'import')" errors during env changes
- Maintains integrated dev server reliability
- Add consistent blue accent styling to SQL cell type selector
- Matches AI cell purple accent pattern with proper background, border, and text colors
- Softer hover effects that mute rather than intensify colors …
> Fix Cloudflare deployment config and stabilize dev environment

- package.json
- pnpm-lock.yaml
- src/Root.tsx
- src/components/auth/UserProfile.tsx
- src/components/notebook/DebugPanel.tsx
- src/components/notebook/MobileOmnibar.tsx
- src/components/notebook/NotebookViewer.tsx
- src/components/notebook/cell/AiCell.tsx
- src/components/notebook/cell/CodeCell.tsx
- src/components/notebook/cell/MarkdownCell.tsx
- src/components/notebook/cell/SqlCell.tsx
- src/livestore.worker.ts
- src/schema.ts
- test/edge-cases.test.ts
- test/integration/execution-flow.test.ts
- test/integration/reactivity-debugging.test.ts
- Update @runt/schema to ^0.7.1
- Create local schema factory in src/schema.ts
- Add `actorId` attribution to all event commits
- Update all schema imports to use local factory
- Fix test imports to use new schema pattern
- Remove deprecated presenceSet event usage
> feat: upgrade to runt 0.7.1 with schema factory and attribution

- src/components/notebook/NotebookViewer.tsx
- wrangler.toml
Show runtime agents as actors on the document too:
> Bubbles with personality

- src/components/notebook/VirtualizedCellList.tsx
- src/components/notebook/cell/shared/CellContainer.tsx
Improves notebook layout by adding proper spacing between cells.
Changes:
- Modified VirtualizedCellList.tsx to reduce unnecessary spacing
- Updated CellContainer.tsx for better cell spacing
Files changed: 2 files, 2 insertions(+), 8 deletions(-)
> Reduce cell spacing

- src/components/notebook/NotebookViewer.tsx
- src/components/notebook/VirtualizedCellList.tsx
- src/components/notebook/cell/CellAdder.tsx
- src/components/notebook/cell/shared/CellContainer.tsx
- src/components/ui/button.tsx
- Color the buttons for adding cells
- Create reusable button coloring styles
> Color the buttons for adding cells

- src/Root.tsx
- src/components/auth/AuthGuard.tsx
- src/util/domUpdates.ts
- vite-plugins/inject-loading-screen.ts
- vite.config.ts
Implements the seamless loading experience following the incremental approach outlined in HANDOFF-REVISED.md.
- **Zero white flash**: Bunny logo appears instantly on page load
- **Smooth stage transitions**: "Initializing..." → "Checking Authentication..." → "Loading Notebook..."
- **Perfect animation handoff**: Static HTML cleanly transitions to React portal animation
- **All existing animations preserved**: Flying bunny and portal expansion work perfectly
- **Static HTML injection**: Vite plugin injects loading screen into index.html at build time
- **Asset preloading**: High-priority preloads for all logo images (bunny.png, shadow.png, runes.png, bracket.png)
- **Transparent AuthGuard**: Eliminates competing loading states during auth check
- **Coordinated handoff**: Static screen …
> Implement seamless loading experience

- vite.config.ts
Went a little overkill here with loaded deps and broke the load. Relying more on `import()` instead.
> Fix effect library initialization by keeping it in vendor chunk

- src/Root.tsx
- src/components/auth/AuthGuard.tsx
- src/components/auth/AuthorizePage.tsx
- src/components/auth/LoginPrompt.tsx
- src/components/loading/LoadingState.tsx
- src/components/logo/RuntLogo.tsx
- src/index.css
- src/util/domUpdates.ts
Fixes some amount of the auth loading jank when signing up a new account with the local oidc provider.
- During auth loading, users would see a black circle with just "Loading..." text when rabbit logo images hadn't loaded yet
- Jarring transitions between different auth states
- Inconsistent styling between static HTML loading screen and React components
- Changed `AuthGuard` to render a React `LoadingState` component instead of returning `null` during auth loading
- Added `skipStaticRemoval` prop to prevent premature removal of the static loading screen
- Ensures users always see the animated rabbit logo, not just text
- Login page: Staggered animations for logo, title, and form with configurable delays
- Create Account page: Matching entry animations for consistency
- Cross-fade …
> Address (some) of the animation jank during page transitions

- package.json
- pnpm-lock.yaml
> update to 0.9.0

- package.json
- pnpm-lock.yaml
one more iceberg to solve global warming
> Bump runt to 0.9.2

- src/components/notebook/cell/shared/Editor.tsx
Eliminates the awkward duplicate CodeMirrorEditor pattern in the mobile maximize feature by using a fixed overlay approach instead of DOM movement. This simplifies the component architecture while maintaining clean separation between CodeMirrorEditor and Editor concerns.
> Refactor Editor maximize to eliminate duplicate instances

- src/components/notebook/CellList.tsx
- src/components/notebook/NotebookViewer.tsx
- src/components/notebook/cell/Cell.tsx
- src/components/notebook/cell/ExecutableCell.tsx
- src/components/notebook/cell/MarkdownCell.tsx
- src/hooks/useDeleteCell.ts
This PR eliminates the `onDeleteCell` prop drilling chain by implementing cell-level deletion logic, providing better UX and cleaner architecture.
- **Keyboard deletion** (backspace in empty cell): Focuses previous cell (or next if first cell)
- **Click deletion** (delete button): Clears focus entirely
- Handles edge cases (single cell, first cell, last cell)
- **Removed `onDeleteCell` from all interfaces**: `CellListProps`, `CellProps`, `ExecutableCellProps`, `MarkdownCellProps`
- **Eliminated prop drilling chain**: `NotebookViewer` → `CellList` → `Cell` → cell types → `CellControls`/`useCellKeyboardNavigation`
- **Removed centralized `deleteCell` function** from `NotebookViewer`
- Each cell now handles its own deletion using:
- `useStore()` - commits delete events
- …
> refactor: eliminate onDeleteCell prop drilling with cell-level deletion

- src/components/notebook/NotebookViewer.tsx
https://github.com/user-attachments/assets/1eef7dc2-62b5-46ff-b158-0a8b7ea46324
> Limit user bubbles

- backend/entry.ts
- backend/hono-entry.ts
- backend/local-oidc-routes.ts
- backend/sync.ts
- test/hono-entry-integration.test.ts
- test/local-oidc-routes.test.ts
Migrate the local oidc routes to hono too
> Hono OIDC Route

- src/Root.tsx
No lazy loading for authorize pages.
> ensure auth pages always loaded

- backend/trpc/index.ts
Should fix this error (but for trpc)
> Fix too many variables SQL error

- src/components/notebook/RuntimeHelper.tsx
- src/components/notebooks/NotebookPage.tsx
- src/components/notebooks/notebook/TitleEditor.tsx
- remove created and updated at
- metadata always one row + scroll
- prevent runtime helper from scrolling page
- single line page title
- wrap nav contents on mobile
> Responsive tweaks

- src/components/notebooks/NotebookCard.tsx
- src/components/notebooks/NotebookDashboard.tsx
- src/components/ui/DateDisplay.tsx
https://github.com/user-attachments/assets/9d16fbf0-0c4e-4108-81b9-c5a590b6a1c2
> Show relative date

- backend/trpc/db.ts
- backend/trpc/index.ts
- src/components/notebooks/ColorPicker.tsx
- src/components/notebooks/NotebookPage.tsx
- src/components/notebooks/TagActions.tsx
- src/components/notebooks/TagColorPicker.tsx
- src/components/notebooks/TagCreationDialog.tsx
- src/components/notebooks/TagEditDialog.tsx
- src/components/notebooks/TagSelectionDialog.tsx
- [Fix tag selection button](https://github.com/runtimed/anode/commit/87d99656abe4caa97bf4973c2b46ffb090e14cfd)
- [Allow selecting tags in notebook itself](https://github.com/runtimed/anode/commit/3a61c4763c865a843bd6cab374bf95692b259749)
https://github.com/user-attachments/assets/d3dcc8d2-ec97-465f-af42-4f29fc6434b9
> Tagging improvements

- src/components/notebooks/NotebookDashboard.tsx
Only show a new notebook button as we don't have templates or imports yet.
> new notebook button standalone

- src/components/livestore/CustomLiveStoreProvider.tsx
just a little touch up for the linter
> pluck user out

- src/components/notebook/NotebookSidebar.tsx
- src/components/notebooks/dashboard/NotebookDashboard.tsx
- src/components/notebooks/notebook/NotebookPage.tsx
Move the git commit hash into the help panel. While I was at it I linked our repo here.
> move git commit hash and project info to Help Panel

- iframe-outputs/src/components/IframeReactApp.tsx
- src/components/notebook/cell/shared/OutputsErrorBoundary.tsx
- src/components/outputs/MaybeCellOutputs.tsx
- src/components/outputs/shared-with-iframe/comms.ts
- Remove dividers
- Remove console logs
> Small iframe tweaks

- package.json
- pnpm-lock.yaml
- src/components/outputs/shared-with-iframe/MarkdownRenderer.tsx
> HTML support in Markdown

- packages/schema/jsr.json
- packages/schema/package.json
Going to tag this after merge to test publish workflow out.
> Bump schema version to v0.1.9

- .github/workflows/publish.yml
- packages/schema/jsr.json
- packages/schema/package.json
11th times the charm, as the saying goes
> Rel 0.1.11

- backend/sync.ts
- packages/agent-core/src/config.ts
- packages/agent-core/src/index.ts
- packages/agent-core/src/runtime-agent.ts
- packages/agent-core/src/store-factory.ts
- packages/agent-core/src/sync-types.ts
- packages/agent-core/src/types.ts
- src/components/notebooks/notebook/NotebookPage.tsx
- src/main.tsx
- src/runtime/README.md
- src/runtime/console-launcher.ts
- src/runtime/setup-console-launcher.ts
I've simplified down to making the browser agents launch in the chrome devtools (for now) as it makes it easier to focus on just getting the agent connected properly. This feels like a good approach before I dive back into hooking it up in the UI.
> Browser console runtime launcher

- packages/agent-core/jsr.json
- packages/agent-core/src/runtime-agent.ts
Create import map for agent core, fix `setInterval` return type to match all environments.
> Fix agent core jsr publishing

- packages/pyodide-runtime/package.json
- packages/pyodide-runtime/src/LocalRuntimeAgent.ts
- packages/pyodide-runtime/src/index.ts
- packages/pyodide-runtime/src/pyodide-worker.ts
- packages/pyodide-runtime/src/pypackages.ts
- packages/pyodide-runtime/src/runt_runtime.py
- packages/pyodide-runtime/src/runt_runtime_bootstrap.py
- packages/pyodide-runtime/src/runt_runtime_display.py
- packages/pyodide-runtime/src/runt_runtime_init.py
- packages/pyodide-runtime/src/runt_runtime_interrupt_patches.py
- packages/pyodide-runtime/src/runt_runtime_registry.py
- packages/pyodide-runtime/src/runt_runtime_shell.py
- pnpm-lock.yaml
A little more basic additions to the pyodide agent just to make sure the workspace is all hooked up before I do the harder bits.
> Super basic pyodide framing

- src/components/notebooks/NotebookActions.tsx
- src/components/notebooks/SharingDialog.tsx
- src/components/notebooks/notebook/NotebookHeader.tsx
- src/components/notebooks/notebook/NotebookPage.tsx
Keep forgetting it's called "modal", so making more consistent with other dialogs
> Rename sharing modal to dialog

- src/components/notebooks/NotebookActions.tsx
- src/components/notebooks/SharingDialog.tsx
- src/components/notebooks/notebook/NotebookPage.tsx
- src/hooks/use-notebooks.ts
- Add copy link
- No longer auto-closing dialog when adding a user / removing a user (this prompted the revamp)
- No longer briefly flashing that a collaborator is already added
- Break up into multiple components
- Cleaner invalidation
Video from preview.runt.run at double speed:
https://github.com/user-attachments/assets/e54d1abb-9291-46b2-a8f2-2642c14f1a97
> Sharing dialog revamp

- src/components/auth/ApiKeysDialog.tsx
- src/hooks/useApiKeys.ts
- test/api-keys.test.ts
Listing was mostly useless. Time for just one key to change out as needed.
> Simplify API keys down to one

- src/components/notebook/cell/shared/PlayButton.tsx
> make stop button more obvious

- package.json
- pnpm-lock.yaml
- vite.config.ts
Doing dev mode by default so we don't need to set env variables, especially when running locally. The two won't be that different anyways
> Add bundle visualizer plugin

- src/auth/AuthGuard.tsx
- src/auth/LoginPrompt.tsx
- src/auth/auth-provider-name.ts
- src/components/ui/Spinner.tsx
- src/components/ui/button.tsx
- test/auth-provider-name.test.ts
We used to show a provider name from the domain. Now showing the domain itself
Added some cleanup and tests
With provider:
https://github.com/user-attachments/assets/769a9fe0-9b05-471e-8c4f-5ebf0f42f825
Local:
https://github.com/user-attachments/assets/02962675-90a7-4714-b762-9e6e477c453b
> Clean up login, reduce bundle size

- src/components/notebooks/notebook/NotebookHeader.tsx
https://github.com/user-attachments/assets/880778b4-f6ed-4fa3-be30-a6613be7a2b6
> Move share button out of metadata area
