- .zed/tasks.json
- AGENTS.md
- package.json
- packages/docworker/tsconfig.json
- packages/schema/package.json
- packages/schema/src/schema.ts
- packages/schema/tsconfig.json
- packages/web-client/src/Root.tsx
- packages/web-client/tsconfig.json
- packages/web-client/vite.config.d.ts
- packages/web-client/vite.config.js
- tsconfig.json
* Allow packages to rely on schema typescript directly
* Include "deprecated" event both to fix local storage and to show _how_ to deprecate events so event logs materialize properly
* Begin `AGENTS.md` to document project hackery
> Composite ts

- AGENTS.md
- HANDOFF.md
- README.md
- docs/TESTING.md
- docs/kernel-connection-guide.md
- docs/quick-start-kernel.md
- packages/dev-server-kernel-ls-client/src/index.ts
- packages/dev-server-kernel-ls-client/src/mod-reactive.ts
- packages/dev-server-kernel-ls-client/test/kernel-adapter.test.ts
- packages/dev-server-kernel-ls-client/test/setup.ts
Bring reactive kernel back and update docs.
Big thing to note was that **committing events from within reactive subscription callbacks** was causing LiveStore's internal reactive system to conflict with itself. By deferring the commits with `setTimeout(..., 0)`, we let the current reactive cycle complete before starting new ones. I need to check with the LiveStore folks on if that is the right approach.
> Reactive kernel

- packages/web-client/src/components/notebook/RichOutput.tsx
> toss the `flex justify-center` so images are left justified

- packages/dev-server-kernel-ls-client/src/pyodide-kernel.ts
Only emit one execution result since we use the callback machinery.
> Don't send an extra result onward

- packages/dev-server-kernel-ls-client/src/kernel-adapter.ts
- packages/dev-server-kernel-ls-client/test/kernel-adapter.test.ts
- shared/schema.ts
- test/fixtures/index.ts
- test/integration/execution-flow.test.ts
- test/integration/reactivity-debugging.test.ts
- Add `cellId` to `ExecutionCompleted` and `ExecutionCancelled` event schemas
- Remove `ctx.query()` calls from materializers to make them pure functions
- Update all event commits to include cellId in the payload
- This fixes `LiveStore.UnexpectedError` about materializer hash mismatch
The issue was that materializers were using `ctx.query()` to look up `cellId` during materialization, making them non-deterministic. LiveStore requires materializers to be pure functions without side effects -- all data must be passed via the event payload.
> Fix materializer hash mismatch by making Execution* materializers deterministic

- packages/dev-server-kernel-ls-client/src/kernel-adapter.ts
- packages/dev-server-kernel-ls-client/test/kernel-adapter.test.ts
- shared/schema.ts
- test/fixtures/index.ts
- test/integration/execution-flow.test.ts
- test/integration/reactivity-debugging.test.ts
Fixes #34.
- Add `cellId` to `ExecutionStarted` event schema
- Remove `ctx.query()` call from `ExecutionStarted` materializer
- Update all cell event commits to include `cellId` in the payload
This fixes another potential source of materializer hash mismatches that
could cause LiveStore to shut down unexpectedly. All materializers are
now deterministic and side-effect free.
> More materializers

- docs/ui-enhancements-demo.md
- packages/dev-server-kernel-ls-client/src/kernel-adapter.ts
- packages/dev-server-kernel-ls-client/test/kernel-adapter.test.ts
- packages/web-client/src/components/notebook/NotebookViewer.tsx
- shared/schema.ts
- test/edge-cases.test.ts
- test/fixtures/index.ts
- test/integration/execution-flow.test.ts
- test/integration/reactivity-debugging.test.ts
Show runtime heartbeat, capabilities.
More tests! No more are skipped.
> Kernel Health Monitoring & Testing Suite

- HANDOFF.md
- docs/IMPLEMENTATION_SUMMARY.md
- docs/ai-features.md
- examples/ai-context-demo.md
- packages/dev-server-kernel-ls-client/src/kernel-adapter.ts
- packages/dev-server-kernel-ls-client/test/kernel-adapter.test.ts
AI cells now see execution results, not just source code.
- Enhanced NotebookContext to include filtered outputs (text/plain, text/markdown)
- Updated context gathering to query outputs table reactively
- Added test coverage for all output types
- Basic filtering preserves token efficiency while maximizing context value
> feat: integrate cell outputs into AI context

- packages/dev-server-kernel-ls-client/src/kernel-adapter.ts
- packages/web-client/package.json
- packages/web-client/src/components/notebook/NotebookViewer.tsx
- pnpm-lock.yaml
Fixes kernel status showing red despite being connected and eliminates "-1s ago" heartbeat display.
- Send immediate heartbeat on kernel startup → green status in 1-2s instead of 30s
- Add "connecting" state → blue "Connecting..." instead of red "Disconnected" 
- Replace timer-based display with reactive date-fns formatting
- Remove INITIAL_SYNC_DELAY and other timing delays
Clean kernel connection experience without confusing red-while-working states.
> Fix kernel connection UI timing issues

- packages/dev-server-kernel-ls-client/src/kernel-adapter.ts
- packages/dev-server-kernel-ls-client/test/kernel-adapter.test.ts
- packages/web-client/src/components/notebook/AiCell.tsx
- packages/web-client/src/components/notebook/Cell.tsx
- packages/web-client/src/components/notebook/SqlCell.tsx
- shared/schema.ts
- test/edge-cases.test.ts
- test/fixtures/index.ts
- test/integration/execution-flow.test.ts
- test/integration/reactivity-debugging.test.ts
- Add timing fields to cells and `executionQueue` tables
- Track `startedAt`, `completedAt`, and `executionDurationMs` in events
- Replace hardcoded timing displays with actual execution times
- Show milliseconds for <1s executions, seconds for longer ones
- Include timing data in error cases for complete visibility
- Update tests to include required timing fields
Replaces fake timing values ('0.3s', '1.2s', '42ms') with real performance data.
> Add execution timing tracking

- packages/pyodide-runtime-agent/package.json
- packages/pyodide-runtime-agent/src/cache-utils.ts
- packages/pyodide-runtime-agent/src/pyodide-kernel.ts
- packages/pyodide-runtime-agent/src/runtime-agent.ts
- packages/web-client/package.json
- packages/web-client/src/components/notebook/AiCell.tsx
- packages/web-client/src/components/notebook/AnsiOutput.tsx
- packages/web-client/src/components/notebook/Cell.tsx
- packages/web-client/src/components/notebook/RichOutput.tsx
- packages/web-client/src/util/ansi-cleaner.test.ts
- packages/web-client/src/util/ansi-cleaner.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
- test-rich-output.py
- test-terminal-detection.py
Python execution in Anode was producing messy ANSI escape codes in error outputs, making them hard to read. Additionally, libraries like `rich` weren't producing colored output because Pyodide doesn't report as a proper terminal environment.
**Before:**
```
[0;31mAttributeError  [0m[39m[0mTraceback (most recent call last)
```
**After:**
- 🤖 **AI models**: Get clean, parseable text without escape codes
- 👨‍💻 **Users**: See beautiful colored terminal output as intended
1. **Raw ANSI preserved** in LiveStore events for authentic terminal experience
2. **AI context cleaning** strips ANSI codes when building model prompts
3. **User display rendering** converts ANSI to beautiful React components
- Configure Pyodide to report as proper terminal (`xterm-256color`)
- Mock `sys.stdout.isatty()` to …
> Implement Dual-Mode ANSI Handling: Clean for AI, Colored for Users

- packages/web-client/src/Root.tsx
- packages/web-client/src/components/notebook/NotebookViewer.tsx
- Convert New Notebook button to a proper link element
- Remove unused onNewNotebook callback pattern
- Use browser's native cmd-click behavior for new tab functionality
> feat: enable cmd-click for New Notebook to open in new tab

- packages/docworker/package.json
- packages/docworker/wrangler.toml
CI deployment failing because it expects `anode-docworker-prototype` but default config used fake database ID.
**Solution**: 
- Make prototype environment the default in `wrangler.toml` (uses real database ID)
- Move development config to `[env.development]` section  
- Update local dev script to use `--env development` (rely on localized database)
**Result**:
- ✅ CI deploys to production with real database
- ✅ Local dev stays safe with fake database  
- ✅ No workflow changes for developers
Fixes deployment error: `binding DB of type d1 must have a database that already exists
> Fix Cloudflare deployment configuration

- packages/docworker/package.json
- packages/docworker/wrangler.toml
- Set docworker .env AUTH_TOKEN to match web client's insecure-token-change-me
- Restructure wrangler.toml: development as default, production as named env
- Add AUTH_TOKEN to wrangler.toml vars for consistency
- Fix package.json dev script to not specify --env development
- Update deploy script to target --env production explicitly
> Make local dev wrangler the default, production as named env

- src/components/outputs/ImageOutput.tsx
Simple fix for #84 - removes hardcoded 400px maxHeight from ImageOutput component.
**Change:** Remove maxHeight: 400px style constraint
**Result:** Images display at full natural size
**Preserves:** Zoom functionality and responsive max-width
Fixes #84
> fix: remove height limit from image outputs

- src/components/notebook/Cell.tsx
- src/components/notebook/NotebookViewer.tsx
Improves mobile experience by enhancing textarea sizing and removing extraneous UI elements.
**Textarea Improvements:**
- Mobile textarea now starts at single line height (~2.5rem) instead of wasting space
- Grows intelligently with content up to 40vh maximum height
- Added maximize/minimize button for full-screen editing on mobile
- Smooth transitions and overlay for maximized mode
- Desktop experience unchanged
**UI Cleanup:**
- Hide keyboard shortcuts on mobile (saves vertical space)
- Hide 'Add a new cell' text on mobile
- Remove 'Owner: current-user' display entirely (all platforms)
- Cleaner, more focused mobile interface
Closes #105
Closes #81  
Closes #107
> Enhance mobile textarea experience and clean up UI

- docs/local-auth-testing.md
- package.json
- src/auth/google-auth.ts
- src/auth/useGoogleAuth.ts
Resolves the user pain point of having to re-authenticate every ~5 minutes.
- **Event-driven auth updates**: Replace 1-second polling with immediate response to auth state changes
- **Extended session duration**: Increase cookie expiration from 1 day to 7 days  
- **Reduced false expiration**: Lower preemptive token clearing from 5 minutes to 1 minute
- **Improved performance**: Eliminate continuous polling overhead
- **Better reliability**: Add token change notifications throughout validation logic
- Users stay logged in for up to 7 days instead of ~5 minutes
- Immediate auth state updates instead of polling delays
- Better performance with no background auth requests
- Seamless notebook sessions across browser restarts
Added `pnpm dev:prod` script and documentation for testing auth …
> Fix auth session management to eliminate frequent re-authentication

- src/hooks/useCellKeyboardNavigation.ts
This implements what I call "Fluid Document" keyboard navigation behavior for cells, creating a more natural editing experience similar to chat applications.
**Arrow Up**: First moves to beginning of cell, then to previous cell
**Arrow Down**: First moves to end of cell, then to next cell
Starting with cursor mid-cell:
```
import pandas as pd |
pd.read_csv("example.csv")
```
Press ↑ once cursor moves to start of current cell:
```
|import pandas as pd
pd.read_csv("example.csv")
```
Press ↑ again and the cursor moves to the previous cell.
This prevents accidental cell navigation when you're just trying to move within your code. Instead of jumping between cells unexpectedly, you get a predictable two-step process:
1. Navigate to the edge of your current content
2. Then move between cells …
> Fluid Document Navigation

- src/components/notebook/AiCell.tsx
- src/components/notebook/Cell.tsx
- src/components/notebook/CodeMirror.tsx
- src/components/notebook/SqlCell.tsx
- src/hooks/useCellContent.ts
- src/hooks/useCellKeyboardNavigation.ts
Problem: Navigating between cells felt sluggish and would jump to the wrong cells, as if CodeMirror was hijacking the active cell and consuming more events than it needed to.
Solution: Focus CodeMirror when autoFocus prop changes so there wouldn't be a race condition between React state and CodeMirror's internal focus handling. For the previous and next cell keymap returns, return true when arrow keys trigger cell nav so that CodeMirror isn't also processing the key.
For good measure, I also memoized the extensions array and callbacks to prevent unnecessary re-renders.
> Fix CodeMirror focus management and cell navigation jank

- src/components/outputs/SvgOutput.tsx
Allow for tall plots, otherwise they get truncated.
> toss max height on svg

- src/components/notebook/NotebookViewer.tsx
- src/hooks/useCellFocus.ts
Fixes #130
When deleting a cell, focus was incorrectly jumping to the first cell due to aggressive auto-focus behavior.
- Added  to track focus history in both  and  hook
- Modified auto-focus logic to only focus first cell on initial notebook load
- After cell deletion, focus is cleared and user stays in current viewport position
- Create notebook with many cells
- Scroll down and delete a cell
- Focus should clear without jumping to top
> Fix delete cell focus teleporting to top

- docs/README.md
- docs/technologies/README.md
- docs/technologies/deno.md
- docs/technologies/livestore.md
- docs/technologies/pyodide.md
Anode is using some newer technologies (and will probably pick up some other new concepts in the future). This provides a getting started overview, along with some links to go deeper as needed.
This fills an onboarding gap where new developers need to understand both our codebase and what it's relying on
> Add documentation about technologies used

- src/components/notebook/AiCell.tsx
- src/components/notebook/Editor.tsx
- src/components/notebook/codemirror/CodeMirrorEditor.tsx
- src/components/notebook/codemirror/baseExtensions.ts
Use CodeMirror with markdown highlighting and word wrapping for AI cells on desktop. Wanted this so I can write novels to the agent before it goes to town on my data.
> Add CodeMirror to AI cells

- eslint.config.js
- Add separate ESLint config for test files in test/ directory
- Add config for *.test.* files in src/ directory
- Include Node.js and Vitest globals for test environments
- Disable TypeScript project checking for src test files
- Silence noisy rules in test files
> Fix ESLint configuration for test files

- docs/proposals/artifact-service-design.md
Repeat of #151, now that the outputs tables have been migrated in `@runt/schema`.
> bring back artifact service design doc

- .dev.vars.example
This allows us to keep a clean `wrangler.toml` for deployment while `.dev.vars` fills out the local variables for dev runs.
> provide example .dev.vars

- wrangler.toml
Overly redundant with vite's use of `.env.*` but I wanted to see how to persist the build env settings between wrangler and the CloudFlare UI.
> seeing about setting vars for builds in wrangler toml

- .env.example
- AGENTS.md
- CONTRIBUTING.md
- README.md
- package.json
- pnpm-lock.yaml
- src/util/runtime-command.ts
- test/runtime-command.test.ts
- wrangler.toml
Upgrades schema dependency from GitHub reference to JSR package version 0.6.2. Updates runtime command versions across all environments and documentation. All tests passing.
> Upgrade @runt/schema to 0.6.2

- package.json
- pnpm-lock.yaml
- test/edge-cases.test.ts
- Import isInlineContainer type guard from @runt/schema
- Use proper type checking for MediaContainer union types
- Replace unsafe direct property access with type guard checks
- Add specific type assertion for known test data structure
- Update package.json to use jsr:@runt/schema@^0.6.3
- All 60 tests passing ✅
- No TypeScript errors ✅
Rationale for type assertion:
The test creates a specific data structure (largeData) and verifies it comes back correctly. The type assertion documents the expected structure that we know we put in, making the test more readable and type-safe than using 'as any'.
> Fix test type errors and update to JSR package

- src/components/notebook/cell/shared/Editor.tsx
- src/components/notebook/codemirror/baseExtensions.ts
Adding to cm styles so horizontal scrolling doesn't get cut off
After:
> Fix mobile code editor padding

- package.json
- pnpm-lock.yaml
- src/components/outputs/MarkdownRenderer.tsx
> Add github flavored markdown for tables, lists, and footnotes

- src/components/notebook/DebugPanel.tsx
- src/components/notebook/NotebookViewer.tsx
- src/components/notebook/VirtualizedCellList.tsx
Removes uses of `any` and some type assertions by requiring
`readonly` types as props to match livestore query return types.
> Remove potentially unsafe type assertions

- src/components/notebook/cell/MarkdownCell.tsx
- Remove unnecessary `localSource` dependency from useMemo in MarkdownCell component
- Resolves React Hook warning about unnecessary dependency
> Fix unnecessary useMemo dependency in MarkdownCell

- AGENTS.md
- CONTRIBUTING.md
- README.md
- docs/local-auth-testing.md
- package.json
- pnpm-lock.yaml
- scripts/dev-runtime.sh
- Update @runt/schema dependency from 0.7.3 to 0.8.0
- Update @runt/pyodide-runtime-agent references to 0.8.0
- Update all documentation examples to reference 0.8.0
- All tests passing (60/60)
> Update @runt/* packages to 0.8.0

- package.json
- pnpm-lock.yaml
Bringing us up to `main` from runt at `25d7d6e071da3606be9f6d47d0621dfe3856a9de`.
Diff: https://github.com/runtimed/runt/compare/03dab62e0b1f7527cf7ffa623bbc50664ff180be...25d7d6e071da3606be9f6d47d0621dfe3856a9de
> bump runt version

- src/components/notebook/DebugPanel.tsx
- src/components/notebook/NotebookViewer.tsx
- src/components/notebook/cell/AiCell.tsx
- src/components/notebook/cell/CodeCell.tsx
- src/components/notebook/cell/MarkdownCell.tsx
- src/components/notebook/cell/SqlCell.tsx
- src/components/notebook/cell/shared/CellControls.tsx
- src/components/notebook/cell/shared/PlayButton.tsx
- src/queries/index.ts
This establishes `src/queries/index.ts` to have common `queryDb` calls we use with `useQuery`.
The long term goal is to switch all queries to idiomatic React(ive) usage. For now, this just cleans up the debug panel to only have its queries running when open instead of always passing down data from the parent. Way less running now when the debug panel is closed:
https://github.com/user-attachments/assets/656cd850-82de-4197-b366-607d2200e9b3
> Switch DebugPanel to using useQuery

- src/components/auth/AuthGuard.tsx
Critical fix for auth flow regression introduced by seamless loading changes.
Users getting stuck at "Checking Authentication..." screen when auth fails or login is required. The static loading screen never gets removed, preventing access to login form.
When we made AuthGuard transparent during loading (return `null`), we removed the logic that handles transitioning away from the loading state when auth fails.
- **Remove static loading screen** when auth check completes (regardless of success/failure)
- **Ensure login screen shows** properly when auth fails
> Fix auth flow getting stuck at 'Checking Authentication'

- tsconfig.node.json
Add vite-plugins/**/*.ts to tsconfig.node.json include patterns to resolve: 'File is not listed within the file list of project' error
> Fix TypeScript config to include vite-plugins directory

- src/components/auth/AuthRedirect.tsx
The OIDC callback route was showing the static loading screen overlay with "Initializing..." instead of the AuthRedirect component's "Logging in..." UI. This PR removes the static overlay when the AuthRedirect component mounts, allowing users to see the proper authentication flow UI.
> Fix OIDC route stuck at 'Initializing...' loading screen

- src/Root.tsx
- src/components/auth/AuthGuard.tsx
- src/components/loading/LoadingState.tsx
- src/components/notebook/NotebookLoadingScreen.tsx
- vite.config.ts
Break up the routes into dynamic `import()`s, remove manual Vite chunking config, and clean up timers in loading animations. This reduces the initial bundle to 947KB, which when gzipped is ~292KB.
>  Implement declarative code splitting with dynamic imports

- src/Root.tsx
- src/components/notebook/NotebookLoadingScreen.tsx
- src/components/notebook/NotebookViewer.tsx
- Remove setTimeout from NotebookLoadingScreen portal animation
- Remove unnecessary header runes animation (portal covers screen)
- Simplify component props by removing showIncomingAnimation/onAnimationComplete
- Clean up unused animation state and imports
- All animations now properly chained through React Spring's onRest callbacks
Final cleanup of all the other animation bits introduced in the past day.
> Refactor animation system to use React Spring chaining

- PM2-SETUP.md
- ecosystem.config.json
- Introduced a new 'sync' process in ecosystem.config.json to run the backend API with the command 'pnpm run dev:sync'.
- Updated PM2-SETUP.md to include instructions for logging and running the new 'sync' process, along with clarifications on architecture options for integrated and separate server setups.
> Add sync process to ecosystem configuration and update PM2 setup documentation

- backend/auth.ts
- backend/local_oidc.ts
- backend/types.ts
- test/backend-local-oidc.test.ts
This will be the primary way going forwards that sub-routes can validate that the user is authorized, information about the user (and in the future things like scopes, api key info etc)
The code in local_oidc in the userinfo endpoint is a good example We can continue to add more helpers around e.g. the error codes as we go on
> Refactor the auth code to support getPassport

- src/components/auth/LoginPrompt.tsx
I needed to copy the .dev.vars.example file again and didn't realize it
I think ideally we have .env defaults that work without any env vars in development and if we do want to make sure we don't forget vars, we should first check that we're in prod
> Add detail to auth issuer error

- wrangler.toml
Fix wrangler.toml configuration warning by adding AUTH_ISSUER to the preview environment vars section. This ensures the preview environment has all required authentication configuration.
> fix: add AUTH_ISSUER to preview environment vars

- src/components/notebook/CellList.tsx
- src/components/notebook/NotebookViewer.tsx
- src/components/notebook/cell/Cell.tsx
- src/components/notebook/signals/focus.ts
This PR eliminates unnecessary re-renders when cell focus changes by optimizing how focus state flows through the component tree.
- **Move focus signals to dedicated module**: Created  for centralized focus state management
- **Eliminate signal prop drilling**: Components now import focus signals directly instead of receiving them as props  
- **Computed boolean props**:  components now receive  instead of subscribing to signals directly
> perf: optimize cell focus rendering by eliminating signal prop drilling

- src/components/notebook/CellList.tsx
Simple cleanup to remove unused legacy virtualization properties from the CellList interface.
**Removed unused props from `CellListProps`:**
- `itemHeight?: number`
- `overscan?: number` 
- `threshold?: number`
**Cleaned up:**
- Removed related comments about virtualization being ignored
- Removed unused destructuring in component implementation
These props were leftover from an earlier virtualization implementation that is no longer in use. They were:
- Never actually used in the component logic
- Never passed by any calling code
- Just adding noise to the interface
> refactor: remove unused legacy virtualization props from CellList

- src/components/notebook/CellList.tsx
- src/components/notebook/EmptyStateCellAdder.tsx
- src/components/notebook/NotebookViewer.tsx
- src/components/notebook/cell/Cell.tsx
- src/components/notebook/cell/CellAdder.tsx
- src/components/notebook/cell/CellBetweener.tsx
- src/components/notebook/cell/ExecutableCell.tsx
- src/components/notebook/cell/MarkdownCell.tsx
- src/components/notebook/cell/shared/CellContainer.tsx
- src/components/notebook/cell/shared/CellControls.tsx
- src/hooks/useAddCell.ts
This PR eliminates complex prop drilling for cell creation by implementing a clean, reusable `useAddCell` hook that handles fractional index management expertly.
- **Expert fractional index handling**: Uses schema's `createCellBetween` for complex positioning logic
- **AI model defaults**: Automatically applies user's preferred AI models to new AI cells  
- **Focus management**: New cells are automatically focused with proper cursor positioning
- **Simplified prefetching**: Removed unnecessary output prefetching complexity
**Before:**
```typescript
interface CellListProps {
cellReferences: readonly CellReference[];
onAddCell: (cellId?, cellType?, position?) => void;
onDeleteCell: (cellId: string) => void; // Already eliminated in previous work
}
interface CellProps {
cellId: string; …
```
> refactor: eliminate onAddCell prop drilling with useAddCell hook

- src/components/notebook/CellList.tsx
- src/components/notebook/cell/Cell.tsx
- src/hooks/useUserRegistry.ts
Fixes a critical performance issue where typing in cells caused massive re-render cascades throughout the entire component tree.
- **Every keystroke triggered 25+ component re-renders**
- Root cause: `useUserRegistry` was returning a new `presentUsers` array reference on every render
- This caused `NotebookViewer` to re-render constantly, cascading to all child components
- Severely impacted typing performance, especially in notebooks with many cells
- **Memoized `presentUsers` array** in `useUserRegistry` hook
- Added `useMemo` with proper dependencies to prevent reference instability
- Maintained all existing functionality while fixing performance
**Before**: 25+ re-renders per keystroke across entire component tree
**After**: 1 re-render per keystroke (just the focused cell)
This …
> perf: fix massive re-render cascade on keystroke by memoizing useUserRegistry presentUsers

- src/Root.tsx
- vite-plugins/iframe-server.ts
- vite-plugins/inject-loading-screen.ts
* Bring back livestore dev tools by not injecting our loading screen on its page
* Allow vite to restart itself by keeping the iframe server continuous
> Vite fixes

- backend/api_keys.ts
- package.json
- pnpm-lock.yaml
Implements:
- GET /api/api-keys
- GET /api/api-keys/:id
- PATCH /api/api-keys/:id
- DELETE /api/api-keys/:id
```sh
code=$(echo '{"firstName":"hello","lastName":"world","email":"test@example.com"}' | base64)
response=$(curl -s -X POST http://localhost:8787/local_oidc/token \
-H "Content-Type: application/x-www-form-urlencoded" \
-d "grant_type=authorization_code" \
-d "client_id=local-anode-client" \
-d "code=$code" \
-d "redirect_uri=http://localhost:5173/auth/callback")
access_token=$(echo "$response" | jq -r '.access_token')
curl -X POST http://localhost:8787/api/api-keys \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $access_token" \
-d '{
"scopes": ["runt:read", "runt:execute"],
"expiresAt": "2024-12-31T23:59:59Z",
"resources": [{"type": "notebook", "id": "123"}], …
```
> Implement the remaining CRUD endpoints for api keys

- iframe-outputs/src/components/IframeReactApp.tsx
- iframe-outputs/src/style.css
- src/components/notebook/NotebookViewer.tsx
- src/components/notebook/cell/ExecutableCell.tsx
- src/components/outputs/MaybeCellOutputs.tsx
- src/components/outputs/shared-with-iframe/SuspenseSpinner.tsx
- src/components/outputs/shared-with-iframe/comms.ts
- src/hooks/useCellOutputs.tsx
- src/util/output-grouping.ts
- Clean up height thrashing in cell input footer (from chevron)
- Show stale output in gray until new outputs are recieved
- Don't send iframe height as often
- Animate output height, and debounce it to limit layout shifts when multiple outputs
- Add half-page spacer below all cells
1. Helps with items added to the end causing the page to expand up when scrolled all the wy down
2. Lets you scroll the last your cell to any position on the page
- Delay output spinner to avoid jank
- Don't accidentally mutate outputs
- Clean up iframe states better:
- Clean up height thrashing in cell input footer (from chevron)
- Show stale output in gray until new outputs are recieved
- Don't send iframe height as often
- Animate output height, and debounce it to limit layout shifts when multiple outputs …
> Iframe refinements

- backend/providers/anaconda-api-key.ts
- Anaconda API was returning 403 Forbidden for requests without User-Agent
- Added User-Agent: 'anode/1.0 (https://app.runt.run)' to all operations:
- Create API key
- List API keys
- Get API key
- Delete API key
- Validate API key (whoami endpoint)
- All API key operations now working in preview and production
- Scope mapping working correctly (runt:execute <-> cloud:write)
> fix: Add User-Agent header to Anaconda API requests

- backend/sync.ts
- src/components/notebook/RuntimeHelper.tsx
- src/util/runtime-command.ts
- test/runtime-command.test.ts
**Changes:**
- WebSocket sync backend now supports API key authentication
- API key authenticated runtime agents can use runtime ID as clientId  
- Runtime command generation uses `LIVESTORE_SYNC_URL` instead of `RUNT_API_KEY`
- RuntimeHelper UI updated: expects users to set `RUNT_API_KEY` in environment
- Tests updated for new command format
**Authentication Flow:**
1. Runtime agent connects with API key
2. Backend validates API key → identifies user  
3. Special case: `runtime: true` + non-service user → allow runtime ID as clientId
4. WebSocket connection established with proper user attribution
**Testing:**
- All tests passing (185 passed)
- Deployed and tested on preview with working runtime agent connection
**Status:** Ready for review. Tested end-to-end with RUNT_API_KEY.
> Add API key authentication for WebSocket runtime agents

- backend/routes.ts
**Adds `/api/me` endpoint** that works with any authentication method.
**Purpose:**
- Enable runtime agents and TUI to discover their authenticated user ID
- Provide fail-fast authentication validation before WebSocket connection
- Universal whoami endpoint for all auth types (JWT, API key, service token)
**Returns:**
```json
{
"id": "user-id",
"email": "user@example.com", 
"name": "User Name",
"givenName": "User",
"familyName": "Name",
"isAnonymous": false
}
```
**Next Steps:**
- Update runtime agents to call `/api/me` before LiveStore connection
- Use returned `id` as `clientId` for consistent identity model
- Eliminates special-case clientId validation logic
**Testing:**
- Deployed to preview: `https://preview.runt.run/api/me`
- Works with existing authMiddleware (API key + JWT …
> Add /api/me endpoint for user identity discovery

- eslint.config.js
Makes eslint stop complaining about a console.error we have in the vite config (if getting the local git hash fails).
> enable console global in eslint for vite config

- src/components/outputs/MaybeCellOutputs.tsx
Added this because downloading Vega outputs didn't work because of permission issues. Expecting more problems like this
> Same output permissions as Google Colab

- src/Root.tsx
Update syncPayloadRef to include clientId in useEffect dependency array. The syncPayload was being initialized with the correct clientId but the useEffect was only updating authToken, possibly leaving clientId as an empty string on subsequent auth state changes.
> Fix LiveStore CLIENT_ID_MISMATCH error

- .github/workflows/deploy-preview.yml
- Rename deploy-iframe-outputs.yml to deploy-preview.yml
- Deploy both base app and iframe outputs to preview
- Add all required VITE env vars for base app build
- Use GitHub context for commit hash
- Remove unnecessary env vars from iframe build (doesn't use any)
> Update preview deployment workflow

- src/Root.tsx
- src/components/auth/AuthGuard.tsx
Only show loading animation once we confirm user is authenticated. This prevents showing notebook loading for users who will see login.
> Loading improvements

- src/Root.tsx
- src/components/auth/AuthGuard.tsx
- src/components/auth/AuthProvider.tsx
- src/components/auth/AuthRedirect.tsx
- src/services/openid.ts
- Decouple auth token refresh from LiveStore sync payload
- AuthProvider now stable: only updates on login/logout, not token refresh
- Background token refresh via keepFresh() without reactive chain disruption
- syncPayload uses getter for authToken to avoid object reference changes
- REST APIs get fresh tokens while LiveStore stays connected
- Remove debugging logs from production code
Resolves page reload/restart issues during token lifecycle.
> Fix auth token refresh causing LiveStore restarts

- src/auth/oidc-config.ts
Problem: Authentication fails with "subject from UserInfo response does not match subject in ID Token" error when using Anaconda's OAuth provider.
Root cause: Anaconda's UserInfo endpoint returns non-standard OIDC claim structure with `identity.id` instead of the expected `sub` field. The oidc-client-ts library validates that userInfoClaims.sub === idTokenClaims.sub, but this comparison fails.
Solution: Set loadUserInfo: false in OIDC configuration. The ID token already contains all necessary user claims (sub, email, given_name, family_name), making the UserInfo endpoint call redundant.
> Fix Anaconda auth compat by disabling UserInfo endpoint

- src/auth/oidc-config.ts
- src/pages/OidcCallbackPage.tsx
Problem: react-oidc-context automatic callback processing fails silently, causing users to get stuck on callback page without authentication completing.
Solution: Implement manual callback processing on /oidc route using UserManager.signinCallback() to explicitly exchange authorization code for tokens.
Changes:
- Update OidcCallbackPage to detect callback parameters and manually process token exchange
- Add comprehensive logging for callback flow debugging
- Remove onSigninCallback from OIDC config to avoid conflicts with manual processing
- Add fallback timeouts and error handling for robust callback flow
Impact: Fixes authentication flow in both local development and production environments.
> Fix OIDC callback processing with manual token exchange

- src/auth/AuthGuard.tsx
- src/auth/openid.ts
- src/pages/AuthorizePage.tsx
Toss the `FORCE_LOGIN_SCREEN` bits from way back, rely on the enum to pluck the local storage key.
> Cleanup old testing bits

- src/components/CollaboratorAvatars.tsx
- src/components/notebooks/notebook/NotebookPage.tsx
before:
after:
And also doesn't break if we have non-bot collaborators
> Fix header nav UI issues

- src/components/debug/DebugPanel.tsx
- src/components/notebook/NotebookSidebar.tsx
- src/components/notebook/sidebar-panels/AiPanel.tsx
- src/components/notebook/sidebar-panels/DebugPanel.tsx
- src/components/notebook/sidebar-panels/HelpPanel.tsx
- src/components/notebook/sidebar-panels/MetadataPanel.tsx
- src/components/notebook/sidebar-panels/RuntimePanel.tsx
- src/components/notebook/sidebar-panels/config.ts
- src/components/notebook/sidebar-panels/index.ts
- src/components/notebook/sidebar-panels/types.ts
- src/components/notebooks/TagBadge.tsx
- Create separate component files for each sidebar panel (metadata, ai, runtime, debug, help)
- Add consistent SidebarPanelProps interface and configuration system
- Implement inline tag editing in MetadataPanel with hover controls
- Remove modal-based tag editing in favor of direct panel editing
- Clean up redundant titles (now just 'Tags' instead of 'Tags & Metadata' + 'Current Tags')
> Refactor sidebar to use declarative panel components

- AGENTS.md
- PM2-SETUP.md
- package.json
- scripts/open-browser.sh
- scripts/start-runt-dev.sh
The current setup doesn't properly start notebooks anymore, so removing that for now, and updating a couple other things
- Don't start a nb by default
- Rename command from `dev:runt` to `dev:pm2`
- Add `iframe-outputs` to list of process names
> Update pm2 setup

- .github/workflows/.deploy-reusable.yml
- src/components/notebooks/SharingModal.tsx
- src/components/notebooks/TagBadge.tsx
- src/components/notebooks/dashboard/NotebookDashboard.tsx
- src/components/outputs/MaybeCellOutputs.tsx
- src/components/outputs/shared-with-iframe/RichOutputContent.tsx
- src/components/outputs/shared-with-iframe/SuspenseSpinner.tsx
Spinner padding took up too much space and caused size to be too tall before getting short again
https://web.dev/articles/iframe-lazy-loading
Lots of iframes cause ERR_INSUFFICIENT_RESOURCES
From Claude:
This `ERR_INSUFFICIENT_RESOURCES` error typically occurs when Chrome hits its limits for concurrent connections or resources.
In console:
```
GET http://localhost:8000/@fs/Users/mm/p/anode/node_modules/.vite/deps/chunk-TQJU5BCQ.js?v=a51594a7 net::ERR_INSUFFICIENT_RESOURCE
S
react-syntax-highlighter.js:571  GET http://localhost:8000/@fs/Users/mm/p/anode/node_modules/.vite/deps/chunk-JQOTC3DW.js?v=a51594
a7 net::ERR_INSUFFICIENT_RESOURCES
react-syntax-highlighter.js:574  GET http://localhost:8000/@fs/Users/mm/p/anode/node_modules/.vite/deps/chunk-4XOZMKWA.js?v=a51594
a7 …
```
> Various tweaks that were too small to make PRs out of

- docs/runtime-session-renewal.md
- packages/agent-core/src/runtime-agent.ts
- packages/schema/src/index.ts
- packages/schema/src/tables.ts
- src/hooks/useRuntimeHealth.ts
- src/runtime/README.md
- src/runtime/console-launcher.ts
- test/runtime-session-renewal.test.ts
- Add lightweight session renewal every 15s instead of constant heartbeats
- Add deterministic expiry detection with 30s timeout + 15s tolerance
- Add automatic cleanup of expired sessions on client side
- Update console launcher with renewal status reporting
Key benefits:
- Minimal event spam (1 event per 15s vs constant heartbeats)
- Offline-first compatible (no server dependency)
- Browser crash resilient (no renewals = automatic expiry)
- Works with LiveStore 0.3.x constraints
- Clock skew tolerant with built-in timing flexibility
Resolves runtime aliveness detection for ephemeral browser agents.
> feat: add runtime session renewal system for browser-based runtimes

- .npmrc
`pnpm i -w left-pad` is a workaround that is ok in most case, but not sure if there is one when running shadcn commands like:
```sh
pnpm dlx shadcn@latest add alert
```
> Allow workspace root install

- src/components/notebook/cell/ExecutableCell.tsx
- src/components/notebook/cell/MarkdownCell.tsx
- src/components/notebook/cell/shared/CellContainer.tsx
- src/components/notebook/cell/shared/PlayButton.tsx
Mostly refactored play button styling. Some minor adjustments to the header.
Also works fine when cell collapsed (see play button centering and hover):
https://github.com/user-attachments/assets/cbe4f9d0-7195-454f-a45c-b3081fda3a47
Hover for markdown cells used to have extra bottom padding
> Cleanup play button and header

- src/components/notebooks/dashboard/helpers.ts
Our filtering was too aggressively bringing the user to the shared page instead of what they went to visit explicitly. This now checks the URL param first.
> make filter even smarter by actually determining URL intent

- packages/ai-core/src/mod.ts
- packages/ai-core/src/tool-registry.ts
Tear out the unescaper that was causing problems with valid code inside strings. Modified the system prompt as well to be more tight.
> trim out the newline escaper
